"""What the whole analysis cost — including the parts that happened elsewhere.

Every paid stage already reports its own spend as it runs. That is not the
same as knowing what a run cost, for two reasons this module exists to fix.

**A cached re-run reports $0.00, and that is true but misleading.** Re-running
after a config change costs nothing *now*; it does not make the original
spend disappear. An artifact that records only the most recent run's figure
forgets what producing it actually took, and the ledger silently drifts to
zero the more you work.

**Some of the spend happened outside this tool.** The architecture docs in
`codewiki-docs/` were generated by CodeWiki at roughly $0.52 a document, and
nothing in this pipeline knew that. Quoting "$8.75 for 173 tickets" while
standing on $12 of documents somebody else paid for is not a cost report.

External inputs are declared once with `--docs-cost` and remembered, because
a number nobody can re-derive has to be written down or it is lost.

**Money spent on an artifact that no longer exists still left the account.**
A stage that fails halfway, or a run that is thrown away and redone, bills
for what it did. The surviving artifact records only its own spend, so a
ledger built from artifacts alone understates the real figure — on
2026-09-22 `explain` billed $0.2162 for a partial run that a retry then
overwrote, and the report showed $0.3037. That is not the same kind of
number as a stage cost and is not folded into one: it bought nothing, so
it is reported on its own line and counted only in the total.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class StageCost:
    stage: str
    usd: float
    units: int = 0
    unit_name: str = ""
    external: bool = False
    note: str = ""


@dataclass
class Ledger:
    stages: list[StageCost] = field(default_factory=list)
    findings: dict[str, int] = field(default_factory=dict)
    #: Spend on work no surviving artifact records: a failed or superseded
    #: run. Stage -> usd.
    discarded: dict[str, float] = field(default_factory=dict)

    @property
    def wasted(self) -> float:
        return round(sum(self.discarded.values()), 4)

    @property
    def total(self) -> float:
        return round(sum(s.usd for s in self.stages) + self.wasted, 4)

    @property
    def internal(self) -> float:
        return round(sum(s.usd for s in self.stages if not s.external)
                     + self.wasted, 4)

    def to_dict(self) -> dict[str, Any]:
        return {"stages": [s.__dict__ for s in self.stages],
                "total_usd": self.total, "pipeline_usd": self.internal,
                "discarded_usd": self.discarded, "findings": self.findings}


def _payload(path: Path) -> Any:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("payload")
    except (json.JSONDecodeError, OSError):
        return None


def _sum_cost(rows: Any) -> tuple[float, int]:
    """Total `cost_usd` over a list, or over a dict's values."""
    if isinstance(rows, dict):
        rows = list(rows.values())
    if not isinstance(rows, list):
        return 0.0, 0
    items = [r for r in rows if isinstance(r, dict)]
    return round(sum(float(r.get("cost_usd") or 0) for r in items), 6), len(items)


def build(run: Path, docs_cost: float | None = None,
          docs_note: str = "", declared: dict[str, float] | None = None,
          discarded: dict[str, float] | None = None) -> Ledger:
    run = Path(run)
    led = Ledger()

    for name, unit in (("translations", "ticket"), ("verdicts", "ticket"),
                       ("explain", "feature area")):
        usd, n = _sum_cost(_payload(run / f"{name}.json"))
        if n:
            note = ""
            # A figure lost before the cache stored token counts cannot be
            # recomputed, so it can be declared — and is labelled as declared,
            # because a number somebody typed is not a measurement.
            if not usd and (declared or {}).get(name):
                usd = float(declared[name])
                note = "declared, not measured - the recorded figure was lost"
            led.stages.append(StageCost(name, usd, n, unit, note=note))

    shadow = _payload(run / "shadow.json")
    if isinstance(shadow, dict) and shadow.get("described"):
        usd, n = _sum_cost(shadow["described"])
        led.stages.append(StageCost("shadow --describe", usd, n, "area"))

    # Externally generated documents. Remembered in the run so the figure
    # survives, because nothing here can re-derive it.
    ledger_path = run / "costs.json"
    remembered = _payload(ledger_path) or {}
    external = remembered.get("external") or {}
    stored_declared = remembered.get("declared") or {}
    declared = {**stored_declared, **(declared or {})}
    stored_discarded = remembered.get("discarded") or {}
    discarded = {**stored_discarded, **(discarded or {})}
    led.discarded = {k: float(v) for k, v in discarded.items() if v}
    if docs_cost is not None:
        external["docs"] = {"usd": float(docs_cost), "note": docs_note}

    docs_dir = run.parent.parent / "codewiki-docs"
    n_docs = len(list(docs_dir.glob("*.md"))) if docs_dir.is_dir() else 0
    if external.get("docs"):
        d = external["docs"]
        led.stages.append(StageCost(
            "architecture docs", float(d["usd"]), n_docs, "document",
            external=True, note=d.get("note", "")))
    elif n_docs:
        led.stages.append(StageCost(
            "architecture docs", 0.0, n_docs, "document", external=True,
            note="cost unknown - declare it with --docs-cost"))

    verdicts = _payload(run / "verdicts.json") or []
    ground = _payload(run / "grounding.json") or []
    if isinstance(verdicts, list):
        led.findings = {
            "verdicts": len(verdicts),
            "corroborated": sum(1 for v in verdicts
                                if v.get("verdict") == "corroborated"),
            "contradicted": sum(1 for v in verdicts
                                if v.get("verdict") == "contradicted"),
            "status_conflicts": sum(1 for v in verdicts
                                    if v.get("status_conflict")),
            "grounded": sum(1 for g in ground if g.get("status") == "grounded"),
        }

    if external or declared or discarded:
        ledger_path.write_text(json.dumps(
            {"schema_version": 1, "produced_by": "costs", "meta": {},
             "payload": {"external": external, "declared": declared,
                         "discarded": discarded}},
            indent=1), encoding="utf-8")
    return led


def render(led: Ledger) -> str:
    lines = ["=" * 68, "WHAT THIS RUN COST", "=" * 68, ""]
    width = max((len(s.stage) for s in led.stages), default=10)
    for s in led.stages:
        tag = "  (external)" if s.external else ""
        unit = f"{s.units} {s.unit_name}{'s' if s.units != 1 else ''}" if s.units else ""
        lines.append(f"  ${s.usd:>8.4f}  {s.stage:<{width}}  {unit}{tag}")
        if s.note:
            lines.append(f"{'':>12}  {s.note}")
    for stage, usd in sorted(led.discarded.items()):
        lines.append(f"  ${usd:>8.4f}  {stage:<{width}}  spent on a run that was "
                     f"discarded")
    if led.discarded:
        lines.append(f"{'':>12}  bought nothing that survives - counted in the "
                     f"total, not in the stage above")
    lines += ["", f"  ${led.internal:>8.4f}  this pipeline",
              f"  ${led.total:>8.4f}  TOTAL including external inputs", ""]

    f = led.findings
    if f.get("verdicts"):
        decisive = f["corroborated"] + f["contradicted"]
        lines += ["-" * 68, "WHAT IT BOUGHT", ""]
        lines.append(f"  {f['verdicts']} verdicts, {decisive} of them decisive "
                     f"({f['status_conflicts']} status conflicts)")
        if decisive:
            lines.append(f"  ${led.total / decisive:.3f} per decisive verdict")
        if f["status_conflicts"]:
            lines.append(f"  ${led.total / f['status_conflicts']:.2f} per status "
                         f"conflict — the findings a person acts on")
        lines.append(f"  {f['grounded']} verdicts had every cited name checked "
                     f"against the source, at no cost")
    lines += ["", "  A cached re-run costs nothing and does not reduce these "
              "figures:", "  they record what producing the artifacts took."]
    return "\n".join(lines)
