# Start ProjectPulse with the Jira connection log visible.
#
# Run this in a PowerShell window, leave it open, then use
#   Settings -> Sources
# in the browser. Every Jira attempt prints here as it happens, so one
# screenshot of this window shows what was tried and what came back.
#
#   .\run-with-log.ps1
#
# Tokens are never printed - only the URL, the auth scheme's name and the
# status.

$ErrorActionPreference = "Stop"

# Two secrets this app needs to manage its own credentials:
#   PULSE_SECRET_KEY  encrypts stored tokens (Jira, LLM)
#   PULSE_ADMIN_TOKEN authorises changing them from a browser
#
# Generated once into a gitignored file rather than asked for every time.
# Losing it makes locally stored tokens undecryptable, which on a dev box
# means pasting them again - stated here so that is a known cost and not a
# surprise.
$secrets = Join-Path $PSScriptRoot ".secrets.local.ps1"
if (-not (Test-Path $secrets)) {
    Add-Type -AssemblyName System.Security
    function New-Secret {
        $bytes = New-Object byte[] 32
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        -join ($bytes | ForEach-Object { $_.ToString("x2") })
    }
    @(
        "# Generated by run-with-log.ps1. Local development only - never commit.",
        "`$env:PULSE_SECRET_KEY  = `"$(New-Secret)`"",
        "`$env:PULSE_ADMIN_TOKEN = `"$(New-Secret)`""
    ) | Set-Content -Path $secrets -Encoding utf8
    Write-Host "Generated $secrets" -ForegroundColor Yellow
}
. $secrets

$env:TRACELINK_RUNS = "../../traceability/runs"
$env:PYTHONUTF8 = "1"
$env:PYTHONUNBUFFERED = "1"

Write-Host ""
Write-Host "ProjectPulse - http://127.0.0.1:8080/settings" -ForegroundColor Cyan
Write-Host ""
Write-Host "Admin token (paste once in the browser, on Imports or Models & keys):" -ForegroundColor DarkGray
Write-Host "  $env:PULSE_ADMIN_TOKEN" -ForegroundColor Green
Write-Host ""
Write-Host "Jira connection attempts print below." -ForegroundColor DarkGray
Write-Host ("-" * 72) -ForegroundColor DarkGray

& .venv\Scripts\python.exe -m scripts.serve
