/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * State
         * @description Everything the console renders, in one round trip.
         */
        get: operations["state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description The same call the scheduler and the PM's button make.
         */
        post: operations["sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/write-step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write Step
         * @description Overwrite the demo workbooks at a given point in their story.
         *
         *     A shortcut for the guided tour. Editing the files in Excel by hand does
         *     exactly the same thing and is the more convincing demonstration.
         */
        post: operations["write_step_api_write_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/write-jira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Jira */
        post: operations["write_jira_api_write_jira_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Drop and recreate the schema, so a timeline can be replayed from scratch.
         */
        post: operations["reset_api_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insight Page
         * @description The insight screen itself.
         *
         *     Served as one static file rather than a built bundle: the rest of the UI is
         *     static HTML, judges run the code, and a build step that fails on their
         *     machine would mean no interface at all.
         */
        get: operations["insight_page_insight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gantt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gantt Page
         * @description The schedule view.
         *
         *     Read-only by design - see `api/schemas/gantt.py` for why making it editable
         *     would cost the precision model.
         */
        get: operations["gantt_page_gantt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gantt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Gantt
         * @description Tasks, milestones and dependency edges on one shared time window.
         */
        get: operations["api_gantt_api_gantt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Page
         * @description The arithmetic behind every number, as a page.
         *
         *     A sibling of `/insight` rather than a panel inside it: a PM opens this only
         *     when they want to check a figure, and burying it would make the insight
         *     screen heavier for everyone else.
         */
        get: operations["explain_page_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Explain
         * @description The forward pass, with the working, for one project.
         */
        get: operations["api_explain_api_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insight
         * @description The whole intelligence layer for one project, as one object.
         *
         *     `also` names the same delivery project as other source systems call it - one
         *     project tracked in both Jira and a spreadsheet produces two `projects` rows,
         *     and analysing them separately would throw away every cross-source claim.
         *
         *     This is the endpoint the React insight route renders. It is served here rather
         *     than assembled in the client so that numbers stay born in exactly one place.
         */
        get: operations["insight_api_insight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Calc
         * @description One arithmetic step, written so a reader can redo it on paper.
         *
         *     Four fields rather than one sentence, because a reader needs to see the
         *     operation and the substituted values separately - a formula alone is abstract
         *     and numbers alone are unverifiable.
         */
        Calc: {
            /** Number */
            number: number;
            /** Question */
            question: string;
            /** Formula */
            formula: string;
            /** Substituted */
            substituted: string;
            /** Result */
            result: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * CausalLink
         * @description Why we believe one change explains another.
         */
        CausalLink: {
            /** Template Id */
            template_id: string;
            /** Template Name */
            template_name: string;
            /** Question */
            question: string;
            cause: components["schemas"]["ChainStep"];
            effect: components["schemas"]["ChainStep"];
            /**
             * Evidence Basis
             * @enum {string}
             */
            evidence_basis: "same_entity" | "dependency_edge" | "dependency_path" | "same_project" | "none";
            /** Lag Days Min */
            lag_days_min: number;
            /** Lag Days Max */
            lag_days_max: number;
            /**
             * Ordering Basis
             * @enum {string}
             */
            ordering_basis: "exact" | "bounded_disjoint";
        };
        /**
         * ChainStep
         * @description One end of a causal chain.
         */
        ChainStep: {
            /** Entity Id */
            entity_id: string;
            /** Entity Label */
            entity_label: string;
            /** Field */
            field: string;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            occurred: components["schemas"]["TimeInterval"];
        };
        /**
         * DataQuality
         * @description What the analysis could not use.
         *
         *     Surfaced beside every bundle rather than buried, because a health score
         *     computed on 60% of a project is worse than no score at all.
         */
        DataQuality: {
            /**
             * Rows Rejected
             * @default 0
             */
            rows_rejected: number;
            /**
             * Changes Low Confidence
             * @default 0
             */
            changes_low_confidence: number;
            /**
             * Changes Total
             * @default 0
             */
            changes_total: number;
            /**
             * Baseline Coverage
             * @default 0
             */
            baseline_coverage: number;
            /**
             * Edges Stated
             * @default 0
             */
            edges_stated: number;
            /**
             * Edges Inferred
             * @default 0
             */
            edges_inferred: number;
            /**
             * Edges Dropped
             * @default 0
             */
            edges_dropped: number;
            /**
             * Depends On Inferred Edges
             * @default false
             */
            depends_on_inferred_edges: boolean;
        };
        /**
         * EvidenceRef
         * @description A pointer back to the record a claim came from.
         *
         *     `raw_data_id` is a foreign key by convention into the `_raw_*` table named by
         *     `raw_table`. It is stamped by the extractor and copied unchanged by every
         *     downstream hop - if it is missing, the chain is broken and the finding should
         *     not be shown.
         */
        EvidenceRef: {
            /** Raw Data Id */
            raw_data_id: number | null;
            /** Raw Table */
            raw_table: string | null;
            /** Url */
            url: string | null;
            /** Remark */
            remark: string | null;
            /** Label */
            label: string | null;
        };
        /**
         * ExplainBundle
         * @description Everything needed to check the schedule arithmetic by hand.
         */
        ExplainBundle: {
            /** Project Id */
            project_id: string;
            /** Steps */
            steps: components["schemas"]["ForwardStep"][];
            /** Driving Path */
            driving_path: string[];
            /** Project End Planned */
            project_end_planned: string | null;
            /** Project End Projected */
            project_end_projected: string | null;
            /** Project Slip Days */
            project_slip_days: number | null;
            /** Stated Only End */
            stated_only_end: string | null;
            /**
             * Depends On Inferred Edges
             * @default false
             */
            depends_on_inferred_edges: boolean;
            /**
             * Edges Stated
             * @default 0
             */
            edges_stated: number;
            /**
             * Edges Inferred
             * @default 0
             */
            edges_inferred: number;
            /** Refused Edges */
            refused_edges: components["schemas"]["RefusedEdge"][];
            /** Scalars */
            scalars: {
                [key: string]: unknown;
            };
        };
        /**
         * Finding
         * @description One thing worth a PM's attention, with everything needed to defend it.
         */
        Finding: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "info";
            /** Headline */
            headline: string;
            /**
             * Recommendation
             * @default
             */
            recommendation: string;
            /** Facts */
            facts: {
                [key: string]: string;
            };
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            causal_link: components["schemas"]["CausalLink"] | null;
            rule_trace: components["schemas"]["RuleTrace"] | null;
            /**
             * Evidence Basis
             * @default none
             * @enum {string}
             */
            evidence_basis: "same_entity" | "dependency_edge" | "dependency_path" | "same_project" | "none";
        };
        /**
         * ForwardStep
         * @description One task's forward pass, derived as input -> algorithm -> output.
         */
        ForwardStep: {
            /** Entity Id */
            entity_id: string;
            /** Label */
            label: string;
            /** Title */
            title: string | null;
            /** Start */
            start: string | null;
            /** Duration Days */
            duration_days: number | null;
            /** Driver */
            driver: string | null;
            /** Driver Label */
            driver_label: string | null;
            /** Lag Days */
            lag_days: number | null;
            /** Earliest Start */
            earliest_start: string | null;
            /** Projected End */
            projected_end: string | null;
            /** Planned End */
            planned_end: string | null;
            /** Baseline End */
            baseline_end: string | null;
            /** Propagated Days */
            propagated_days: number | null;
            /** Variance Days */
            variance_days: number | null;
            /** Recorded Slip Days */
            recorded_slip_days: number | null;
            /**
             * Is Inconsistent
             * @default false
             */
            is_inconsistent: boolean;
            /** Inputs */
            inputs: components["schemas"]["Operand"][];
            /** Calc */
            calc: components["schemas"]["Calc"][];
            /** Outputs */
            outputs: components["schemas"]["Operand"][];
        };
        /**
         * GanttBundle
         * @description Everything the schedule view renders, for one project.
         */
        GanttBundle: {
            /** Project Id */
            project_id: string;
            /** Rows */
            rows: components["schemas"]["GanttRow"][];
            /** Milestones */
            milestones: components["schemas"]["GanttMilestone"][];
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** As Of */
            as_of: string | null;
            /** Driving Path */
            driving_path: string[];
            /** Project End Planned */
            project_end_planned: string | null;
            /** Project End Projected */
            project_end_projected: string | null;
        };
        /**
         * GanttMilestone
         * @description A milestone marker, dated from the last task beneath it.
         */
        GanttMilestone: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Planned Date */
            planned_date: string | null;
            /** Baseline Date */
            baseline_date: string | null;
            /** Slipped Days */
            slipped_days: number | null;
            /**
             * At Risk
             * @default false
             */
            at_risk: boolean;
        };
        /**
         * GanttRow
         * @description One task, as a row of bars.
         */
        GanttRow: {
            /** Entity Id */
            entity_id: string;
            /** Label */
            label: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string | null;
            /** Assignee */
            assignee: string | null;
            /** Start */
            start: string | null;
            /** Baseline End */
            baseline_end: string | null;
            /** Planned End */
            planned_end: string | null;
            /** Projected End */
            projected_end: string | null;
            /** Propagated Days */
            propagated_days: number | null;
            /** Recorded Slip Days */
            recorded_slip_days: number | null;
            /**
             * Is Inconsistent
             * @default false
             */
            is_inconsistent: boolean;
            /** Progress */
            progress: number | null;
            /** Milestone Id */
            milestone_id: string | null;
            /** Milestone Name */
            milestone_name: string | null;
            /** Depends On */
            depends_on: string[];
            /**
             * On Driving Path
             * @default false
             */
            on_driving_path: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsightBundle
         * @description Everything the insight screen renders, for one project at one moment.
         */
        InsightBundle: {
            /** Project Id */
            project_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            data_quality: components["schemas"]["DataQuality"];
            /**
             * Narrative
             * @default
             */
            narrative: string;
            /**
             * Narration Source
             * @default template
             * @enum {string}
             */
            narration_source: "template" | "model";
            /** Narration Fallback Reason */
            narration_fallback_reason: string | null;
            /** Context */
            context: {
                [key: string]: unknown;
            };
        };
        /**
         * Operand
         * @description One labelled value, on the way in or out.
         */
        Operand: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * RefusedEdge
         * @description A dependency the graph would not accept, and why.
         *
         *     Surfaced rather than swallowed: an edge silently dropped is a path a PM
         *     thinks exists and the projection does not use.
         */
        RefusedEdge: {
            /** Predecessor */
            predecessor: string;
            /** Successor */
            successor: string;
            /** Reason */
            reason: string;
        };
        /**
         * RuleTrace
         * @description Why a rule fired, in terms a PM can challenge.
         */
        RuleTrace: {
            /** Rule Id */
            rule_id: string;
            /** Conditions */
            conditions: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** StepRequest */
        StepRequest: {
            /**
             * Step
             * @default 0
             */
            step: number;
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Source
             * @default excel
             */
            source: string;
            /** Now */
            now?: string | null;
        };
        /**
         * TimeInterval
         * @description When something happened, honestly.
         *
         *     `lower == upper` only for events from a changelog. Anything derived from
         *     comparing two spreadsheet snapshots is a genuine interval, and collapsing it
         *     to a midpoint would invent precision the source never had.
         */
        TimeInterval: {
            /**
             * Lower
             * Format: date-time
             */
            lower: string;
            /**
             * Upper
             * Format: date-time
             */
            upper: string;
            /**
             * Precision
             * @enum {string}
             */
            precision: "exact" | "bounded";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_step_api_write_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_jira_api_write_jira_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    reset_api_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    insight_page_insight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    gantt_page_gantt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_gantt_api_gantt_get: {
        parameters: {
            query?: {
                project?: string;
                also?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GanttBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_page_explain_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_explain_api_explain_get: {
        parameters: {
            query?: {
                project?: string;
                also?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insight_api_insight_get: {
        parameters: {
            query?: {
                project?: string;
                also?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
