"""Regenerate the function index in WORKLOG.md.

Written because a hand-maintained index is a lie within a day. The narrative half
of WORKLOG.md - what is being worked on right now, and what changed - is written
by a human (or by Claude); everything below the marker is generated from the
source itself, so it cannot drift.

    python -m scripts.index_code            # regenerate
    python -m scripts.index_code --check    # fail if it is stale

Reads the AST rather than importing: an index that requires the package to import
cleanly is useless exactly when you need it most, halfway through a refactor.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WORKLOG = REPO / "WORKLOG.md"

#: Everything below this line in WORKLOG.md is regenerated. Anything above is kept.
MARKER = "<!-- BEGIN GENERATED INDEX -->"

ROOTS = ("app", "scripts")
SKIP_DIRS = {"__pycache__", ".venv", "node_modules"}


def first_line(node: ast.AST) -> str:
    """The first sentence of a docstring, or empty."""
    doc = ast.get_docstring(node) or ""
    line = doc.strip().split("\n", 1)[0].strip()
    return line


def signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = [a.arg for a in node.args.posonlyargs + node.args.args]
    if node.args.vararg:
        args.append("*" + node.args.vararg.arg)
    elif node.args.kwonlyargs:
        args.append("*")
    args.extend(a.arg for a in node.args.kwonlyargs)
    if node.args.kwarg:
        args.append("**" + node.args.kwarg.arg)
    return f"{node.name}({', '.join(args)})"


def describe(path: Path) -> tuple[str, list[str]] | None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return None

    entries: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue  # private helpers are implementation, not interface
            entries.append(f"- `{signature(node)}` - {first_line(node)}")
        elif isinstance(node, ast.ClassDef):
            methods = [
                f"`{m.name}`"
                for m in node.body
                if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))
                and not m.name.startswith("_")
            ]
            tail = f" - methods: {', '.join(methods)}" if methods else ""
            entries.append(f"- **`class {node.name}`** - {first_line(node)}{tail}")

    return first_line(tree), entries


def render() -> str:
    lines = [
        MARKER,
        "",
        "## Function index",
        "",
        "_Generated by `python -m scripts.index_code`. Do not edit below the marker._",
        "",
    ]

    files: list[Path] = []
    for root in ROOTS:
        for path in sorted((REPO / root).rglob("*.py")):
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            if path.name == "__init__.py" and path.stat().st_size < 200:
                continue
            files.append(path)

    for path in files:
        result = describe(path)
        if result is None:
            continue
        summary, entries = result
        if not entries:
            continue
        rel = path.relative_to(REPO).as_posix()
        lines.append(f"### `{rel}`")
        if summary:
            lines.append(f"_{summary}_")
        lines.append("")
        lines.extend(entries)
        lines.append("")

    return "\n".join(lines)


def _compose() -> str:
    existing = WORKLOG.read_text(encoding="utf-8") if WORKLOG.exists() else ""
    head = existing.split(MARKER)[0] if MARKER in existing else existing
    if not head.strip():
        head = "# Worklog\n\n"
    return head.rstrip() + "\n\n" + render()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the index is current without writing (exit 1 if stale)",
    )
    args = parser.parse_args()

    composed = _compose()
    current = WORKLOG.read_text(encoding="utf-8") if WORKLOG.exists() else ""

    if args.check:
        # Deliberately non-zero on stale, so this is usable as a check rather
        # than only as a generator.
        if composed == current:
            print("index is current")
            return
        raise SystemExit("index is stale; run: python -m scripts.index_code")

    WORKLOG.write_text(composed, encoding="utf-8")
    print(f"indexed -> {WORKLOG.relative_to(REPO)}")


if __name__ == "__main__":
    main()
